language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
before_script:
  - "mysql -e 'create database gracehrabi_test;'"
  - "cp ./config/database.yml.travis ./config/database.yml"
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec
