page_title: Grace Hrabi
page_sub_title: Jazz Vocalist
site_email: grace@gracehrabi.com

meta:
  keywords: Grace Hrabi, Grace Hrabi McPhillips, Grace Harabi, Grace Herabi, Hrabi, Jazz, Vocalist, Winnipeg, Manitoba, Music, Eliot Britton, Singer, Trio, Duo, Combo, Jazz Combo, Musician for hire, Wedding, Retirement, Birthday, Party, private function, Live music, live performance, Composer, Arranger, Performer, Collection Get, Ten Too Many, Universty of Manitoba, Faculty of Music, Kevin McPhillips
  description: Grace Hrabi - Vocalist
