page_title: Grace Hrabi
page_sub_title: Jazz Vocalist
site_email: grace@gracehrabi.com
admin_email: admin@gracehrabi.com

meta:
  keywords: Grace Hrabi, Grace Hrabi McPhillips, Grace Harabi, Grace Herabi, Hrabi, Jazz, Vocalist, Winnipeg, Manitoba, Music, Eliot Britton, Singer, Trio, Duo, Combo, Jazz Combo, Musician for hire, Wedding, Retirement, Birthday, Party, private function, Live music, live performance, Composer, Arranger, Performer, Collection Get, Ten Too Many, Universty of Manitoba, Faculty of Music, Kevin McPhillips
  description: Singer Songwriter

google_analytics_key: UA-1111111-1

bandcamp_url: http://gracehrabi.bandcamp.com/album/afraid-of-heights
twitter_url: https://twitter.com/GraceHrabi
soundcloud_url: https://soundcloud.com/grace-hrabi
facebook_url: https://www.facebook.com/GraceHrabiMusic
shopify_admin_url: https://gracehrabi.myshopify.com/admin
shop_url: http://shop.gracehrabi.com
searchlight_url: http://music.cbc.ca/#!/artists/Grace-Hrabi

secret_token: 268e54b5a70a7994ffecef6fa0f9175c856976ffcb295944d1ca12dd7166f223913a37443af743c065c69d571ae1f5f0a1c6a0f33a224253165c0126a11f53a4
